language: node_js
node_js:
- 12.4.0
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- yarn
- yarn build
- echo "Skipping tests"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Le8W66vuRe5J3Wd3akuxiApwrCC++ccUZBUHYoLC3myEhLJOpFuvYMVJaAPjYBTodoHJswC4izsRy6onex3GNY/VDZAr/yklhgDzshHluUrJbd8Ssxe+UZGYuCRmO59kQ2BY3JA/k6MMpm2p4x1krCAtqRqScXSxwIgw3/bFbkVGiu6JfTzuJGrstvO/TaSIm1j5JPNw3Cmmmsi589yl1d7P7+/Uep9gSs8vPP/J79EkYoEAA5HteoQeDJ9TQs2l7TYvLpSQsEtpp3PI4EL7xg+SNcrIR3HLI37vKi7/aILC3eERPdCilQB9AW2LQDZ/r/zTYehdPVesAL4qXmzblG1Cx/t0nkQTNPLkfubi+R5wP8ObIV5QreugOg1Ttl2ZMT+dYkM922vDuGCH1kGwgAMnO2rFYjmXb0NW64a7jO0JBlUVA0filSViq6JePMH6NJy4ObVBCq/VwoSIHu/2905Pv3iwXRJ1YS7Vi3viRP/RUqXyirE30JwAplKJRrlUq8PEmjIgVl5r+1Meo4gcaArvqry2vDMivc0pddHcVXN+YZyWa49keKqcESZ02WTqTbrorWAfeYyL0rB9VKOQSWRW27evzf0MH9rizcYoH4z4TmoZ0e8BwvAMkbavVCYXJfBF8J3gk0KJBb9WxZNcoqs8Rj+oZA7wCEZN1GGOLLU=
