language: node_js
node_js:
- 12.4.0
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- yarn
- yarn build
- echo "Skipping tests"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: I96A39ZrlN4bjviqhb5Ntz3Tyx0c8j8iZxawzl1cQRbBp7eBbFmKno8QmaH8IIw762xhHUz+OKcHZiwszjtxew41cja3RZHymT86JvuBgLozX+l50XxRWSrOI8aDBRCDewfgNE2GDx+ejJCAhlIZmf1YOFzoYnQXSsIgG6vdIM572dfNbGp/XTNOh81ZPebm6aKHn1a+TuZCB+7fLVXmHAaqvFgihFFtDhh8jlYPePksAdmX9TroBePMAh4g0y4jH/Ro4jfStXRha7FH9dUAzMdDJ26FnsyhOPNytvCiMJ+VavTdDR605ryPst9SvwOqyuCYMJD4Miz1PFzak6JdyZla4gUfQr0rIH6LVgarhlP9VlNDwZrWsGwycezJpyJUg6xMhI+Dx7dIYG63TuVPxtY9gGE8dAy41vcmzUT9y23MaBtnsVv/5eomT0dc6hkvUxykIybnwVj06xS2Y2Ky3tkNs2+DKh4dL/6EZvR0K2YIDk/Ayn0u0nFAXk4oA9OQ1I5AMBQtt6HBSKrJ/2Qipjnv7CKpX0jbsmdcwFxJlJynwrnM4FfJdQxTgAM5kMWIXv4tA1+B0hKhbpPG3TJNEL0BXXsaZtsGHIQP07bhVm7smJ4Kk+U+bw1NE/CkDYugWbYObOVpuxm9IhXGccVIZx5v19KgAcPPrAVYgITEWpw=