language: node_js
node_js:
- 12.4.0
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script:
- yarn
- yarn build
- echo "Skipping tests"
env:
  global:
  - secure: QzvAJFXZVVSr9RM72OAO0B43D7t48+ZD1LFsKx/k99+kzBWs1EnpV/jdjqvSbhQc4ZgY0M6fd3MFBcN+V2qdyWPbb0yyBC/ySYMLd+FOy8a5Xn8qjbhxFVVbGzMZ+guDXqwNUEqOQEd/Gcm0BkF/191gr1gNRPE5HnO+AgjMHCYiRPMCb6rdJPBwuZ8L955N00iPyTBfoT7Emx/KoAT50fZzqSzJ4tjx/tsAJH+Rkc4BYLUrxFbfU+b9CaljStCqVxB/8C2UcHsnFIkWll4OG7wikn4+Y2nAo6s4Ih4wP4QeIaZOkNaVFXcKwD7GEKOhPM+S2EqZNkA5hApz6j3WHFiVz41Kfb9eh7vCaUivmbSWeQ+l0e34s+4quik5W2g97X9Os1l9FYKfkZmM2A9mm2n9L+ScHsWU25VR/R7EyGXF5AzWVliVxI7THNHtQ+dUHs58NpgZ+8fGaKdyvvExStwpWt9otWEIA7fKxmM4M91kwxAeDhzB8kQVfI/mV27FU5LBkN3OBYzQiSkaQ0Cb5d0Fz0fBudayakIKkqRa0s5q3uV2FkQ2s4zs6tShAUV81YnNoakfhzFGoat5zv2kOxVr4WSEKrEmY6xOyguYhRn0vmM3B2n7h/zLicThvTLrBhZsQ32AByO1vSgkbBbyfjb6PATQjmM1WRoPfsnCaKA=
  - secure: Le8W66vuRe5J3Wd3akuxiApwrCC++ccUZBUHYoLC3myEhLJOpFuvYMVJaAPjYBTodoHJswC4izsRy6onex3GNY/VDZAr/yklhgDzshHluUrJbd8Ssxe+UZGYuCRmO59kQ2BY3JA/k6MMpm2p4x1krCAtqRqScXSxwIgw3/bFbkVGiu6JfTzuJGrstvO/TaSIm1j5JPNw3Cmmmsi589yl1d7P7+/Uep9gSs8vPP/J79EkYoEAA5HteoQeDJ9TQs2l7TYvLpSQsEtpp3PI4EL7xg+SNcrIR3HLI37vKi7/aILC3eERPdCilQB9AW2LQDZ/r/zTYehdPVesAL4qXmzblG1Cx/t0nkQTNPLkfubi+R5wP8ObIV5QreugOg1Ttl2ZMT+dYkM922vDuGCH1kGwgAMnO2rFYjmXb0NW64a7jO0JBlUVA0filSViq6JePMH6NJy4ObVBCq/VwoSIHu/2905Pv3iwXRJ1YS7Vi3viRP/RUqXyirE30JwAplKJRrlUq8PEmjIgVl5r+1Meo4gcaArvqry2vDMivc0pddHcVXN+YZyWa49keKqcESZ02WTqTbrorWAfeYyL0rB9VKOQSWRW27evzf0MH9rizcYoH4z4TmoZ0e8BwvAMkbavVCYXJfBF8J3gk0KJBb9WxZNcoqs8Rj+oZA7wCEZN1GGOLLU=
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Le8W66vuRe5J3Wd3akuxiApwrCC++ccUZBUHYoLC3myEhLJOpFuvYMVJaAPjYBTodoHJswC4izsRy6onex3GNY/VDZAr/yklhgDzshHluUrJbd8Ssxe+UZGYuCRmO59kQ2BY3JA/k6MMpm2p4x1krCAtqRqScXSxwIgw3/bFbkVGiu6JfTzuJGrstvO/TaSIm1j5JPNw3Cmmmsi589yl1d7P7+/Uep9gSs8vPP/J79EkYoEAA5HteoQeDJ9TQs2l7TYvLpSQsEtpp3PI4EL7xg+SNcrIR3HLI37vKi7/aILC3eERPdCilQB9AW2LQDZ/r/zTYehdPVesAL4qXmzblG1Cx/t0nkQTNPLkfubi+R5wP8ObIV5QreugOg1Ttl2ZMT+dYkM922vDuGCH1kGwgAMnO2rFYjmXb0NW64a7jO0JBlUVA0filSViq6JePMH6NJy4ObVBCq/VwoSIHu/2905Pv3iwXRJ1YS7Vi3viRP/RUqXyirE30JwAplKJRrlUq8PEmjIgVl5r+1Meo4gcaArvqry2vDMivc0pddHcVXN+YZyWa49keKqcESZ02WTqTbrorWAfeYyL0rB9VKOQSWRW27evzf0MH9rizcYoH4z4TmoZ0e8BwvAMkbavVCYXJfBF8J3gk0KJBb9WxZNcoqs8Rj+oZA7wCEZN1GGOLLU=
