---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/blog
  label: Blog Posts
  create: all
  match: "**/*"
  exclude: README.md
upload_dir: ''
public_path: https://res.cloudinary.com/dpw19qolx/image/upload/q_auto,f_auto,g_auto,w_auto,dpr_auto
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: src/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  publish_command: vuepress build -d .vuepress/dist
  output_directory: ".vuepress/dist"
  preview_command: yarn build
